# --- General ---
spring.application.name=Training-Nutrition
server.port=8083

# --- PostgreSQL (Real Database Config) ---
# ??? ????????? ????? ?????????????? ??? ??????? ??????? ??????????
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5434/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate ????????? ??? Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Connection Pool ---
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# --- Redis ---
spring.data.redis.host=localhost
spring.data.redis.port=6381

# --- Elasticsearch ---
app.elasticsearch.enabled=true
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.socket-timeout=30s
spring.elasticsearch.rest.connection-timeout=10s
spring.elasticsearch.rest.read-timeout=30s

# --- Kafka ---
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=nutrition-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# --- Swagger / OpenAPI ---
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# --- Actuator ---
management.endpoints.web.exposure.include=health,info
management.health.probes.enabled=true

# --- Logging ---
logging.level.org.springframework.data.elasticsearch=DEBUG
logging.level.org.springframework.kafka=INFO
logging.level.org.hibernate.SQL=DEBUG
