spring:
  application:
    name: NUTRITION-SERVICE   # имя сервиса для Eureka

  datasource:
    url: jdbc:postgresql://localhost:5434/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6381

  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      auto-offset-reset: earliest
      group-id: nutrition-test-group

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
