spring:
  data:
    elasticsearch:
      enabled: false
    redis:
      repositories:
              enabled: false


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false

  sql:
    init:
      mode: never

  kafka:
    bootstrap-servers: dummy:9092


