apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-service-deployment
  labels:
    app: nutrition-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nutrition-service
  template:
    metadata:
      labels:
        app: nutrition-service
    spec:
      containers:
        - name: nutrition-service
          image: your-registry/training-nutrition:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql-service:5432/mydatabase
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: SPRING_DATA_REDIS_HOST
              value: redis-service
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_ELASTICSEARCH_URIS
              value: http://elasticsearch-service:9200
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"