name: Java CI/CD with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Start Infrastructure
        # Запуск всех контейнеров в фоновом режиме
        run: docker compose up -d

      - name: Wait for Elasticsearch
        # Цикл проверки API: ждем ответа от кластера до 120 секунд
        run: |
          echo "Waiting for Elasticsearch to start..."
          timeout 120s bash -c 'until curl -s http://localhost:9200/_cluster/health | grep -q "\"status\":\""; do echo "Still waiting..."; sleep 5; done'
          echo "Elasticsearch is ready!"
          # Небольшая пауза для завершения инициализации индексов
          sleep 5

      - name: Build and Test with Maven
        # Запуск тестов с передачей переменных окружения для подключения к Docker
        run: mvn clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5434/mydatabase
          SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9094
          SPRING_ELASTICSEARCH_URIS: http://localhost:9200
          SPRING_DATA_REDIS_PORT: 6381

      - name: Stop Infrastructure
        if: always()
        run: docker compose down